# fly.toml app configuration file generated for hg-textharvest-v2 on 2023-12-21T18:11:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hg-textharvest-v2"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
