name: Manual Approval and Production Deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval
        run: echo "Awaiting manual approval"
        timeout-minutes: 4320 # Timeout after 3 days

  deploy-production:
    needs: manual-approval
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Production
        run: fly deploy --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
